project:
  type: website
  output-dir: docs

website:
  title: "Art by Danielle Navarro"
  site-url: https://art.djnavarro.net
  repo-url: https://github.com/djnavarro/art
  search: false
  open-graph: true
  twitter-card:
    creator: "@djnavarro"
    card-style: summary_large_image
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./about/index.qmd
        text: About
      - href: ./gallery/index.qmd
        text: Galleries

# execute:
#  freeze: true

format:
  html:
    page-layout: full
    theme: simplex
    css: styles.css
    toc: true
    include-after-body: plausible.html

