project:
  type: website

website:
  title: "art-quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: ./gallery/index.qmd
        text: Galleries

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

